######################################################################
# Automatically generated by qmake (2.01a) sam. janv. 18 15:39:35 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
