######################################################################
# Automatically generated by qmake (2.01a) lun. oct. 14 22:04:46 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += desktopwindow.h
SOURCES += desktopwindow.c

# X11 XLib
LIBS += -lX11 
