######################################################################
# Automatically generated by qmake (2.01a) sam. oct. 12 14:58:54 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
# add the X11 Xlib
LIBS += -lX11
