######################################################################
# Automatically generated by qmake (2.01a) ven. nov. 29 13:32:37 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
