######################################################################
# Automatically generated by qmake (2.01a) mar. janv. 21 21:07:51 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
