######################################################################
# Automatically generated by qmake (2.01a) mar. oct. 15 19:14:27 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS = programwin.h
SOURCES = programwin.cpp \
	  main.cpp
	

# add the Qt webkit widgets
#QT += webkit

# add the X11 Xlib
#LIBS += -lX11
