######################################################################
# Automatically generated by qmake (2.01a) sam. déc. 7 20:01:37 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialogwindow.h kupasshpairingwizard.h programwin.h
SOURCES += dialogwindow.cpp kupasshpairingwizard.cpp main.cpp programwin.cpp
