######################################################################
# Automatically generated by qmake (2.01a) sam. janv. 18 18:47:13 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
# add the necessary to compile against opencv2

# Input
SOURCES += main.cpp
# add Qwt
CONFIG += qwt

# according to the doc
LIBS += `pkg-config opencv --libs`
