######################################################################
# Automatically generated by qmake (2.01a) ven. janv. 17 14:41:10 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += radio.h
SOURCES += main.cpp radio.cpp
