######################################################################
# Automatically generated by qmake (2.01a) lun. déc. 2 23:35:32 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += kupasshpairingwizard.h
SOURCES += kupasshpairingwizard.cpp main.cpp
