######################################################################
# Automatically generated by qmake (2.01a) mar. janv. 21 09:11:52 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
# add Qwt
CONFIG += qwt
# add OpenCV ( according its doc )
LIBS += `pkg-config opencv --libs`
