######################################################################
# Automatically generated by qmake (2.01a) sam. janv. 18 17:43:38 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

# add Qwt
CONFIG += qwt
