######################################################################
# Automatically generated by qmake (2.01a) sam. oct. 12 14:07:49 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
