######################################################################
# Automatically generated by qmake (2.01a) jeu. nov. 7 08:27:50 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += arduinoqwtwidget.h
SOURCES += arduinoqwtwidget.cpp main.cpp
CONFIG += extserialport qwt

# to display the console window
CONFIG += console
