######################################################################
# Automatically generated by qmake (2.01a) mer. janv. 15 23:48:46 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
# errorfix
INCLUDEPATH += /usr/include/QtMultimediaKit /usr/include/QtMobility

# Input
HEADERS += audiooutput.h
SOURCES += audiooutput.cpp main.cpp

QT      += multimedia
