######################################################################
# Automatically generated by qmake (2.01a) ven. janv. 17 12:56:07 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
# errorfix
INCLUDEPATH += /usr/include/QtMultimediaKit /usr/include/QtMobility

# Input
HEADERS += audioinput.h
SOURCES += audioinput.cpp main.cpp

QT      += multimedia
