######################################################################
# Automatically generated by qmake (2.01a) sam. sept. 7 02:47:46 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS +=
SOURCES += main.cpp
