######################################################################
# Automatically generated by qmake (2.01a) dim. oct. 13 05:01:43 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

# Xlib
LIBS += -lX11
