######################################################################
# Automatically generated by qmake (2.01a) ven. oct. 11 10:25:02 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
