######################################################################
# Automatically generated by qmake (2.01a) jeu. nov. 28 03:46:49 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
