######################################################################
# Automatically generated by qmake (2.01a) ven. déc. 6 11:04:42 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialogwindow.h
SOURCES += dialogwindow.cpp main.cpp
