######################################################################
# Automatically generated by qmake (2.01a) mer. nov. 6 08:50:49 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += arduinowidget.h
SOURCES += arduinowidget.cpp main.cpp
CONFIG += extserialport
