######################################################################
# Automatically generated by qmake (2.01a) mar. janv. 21 12:47:51 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += plotmatrix.h
SOURCES += main.cpp plotmatrix.cpp
# add Qwt
CONFIG += qwt
# add OpenCV ( according its doc )
LIBS += `pkg-config opencv --libs`
