######################################################################
# Automatically generated by qmake (2.01a) dim. janv. 19 12:43:46 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += qwtwidget.h
SOURCES += main.cpp qwtwidget.cpp

# add Qwt
CONFIG += qwt
