######################################################################
# Automatically generated by qmake (2.01a) ven. oct. 11 10:53:02 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += 
SOURCES += main.cpp

# X11 Xlib
LIBS += -lX11
