######################################################################
# Automatically generated by qmake (2.01a) ven. janv. 17 14:38:20 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += /usr/include/QtMultimediaKit /usr/include/QtMobility

# Input
HEADERS += audiorecorder.h
FORMS += audiorecorder.ui
SOURCES += audiorecorder.cpp main.cpp

QT      += multimedia
